version: '3'

services:
  server:
    depends_on:
      - postgres
    env_file: .env_serv
    ports:
      - 1323:1323
    build: cmd

  postgres:
    image: postgres:12.3-alpine
    env_file: .env_postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
